[package]
name = "portfolio"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
trunk = "0.20.2"
wasm-bindgen-futures = "0.4.42"
yew = { version = "0.20", features = ["csr"] }
